_wandb:
    value:
        cli_version: 0.25.1
        e:
            86c178espjtm0w2qo7t5l9964kzlwbc3:
                codePath: runs\q2_4_positional_encoding.py
                codePathLocal: runs\q2_4_positional_encoding.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "569760542720"
                        used: "414932946944"
                email: saisvanik2121@gmail.com
                executable: C:\Users\Abhi\AppData\Local\Programs\Python\Python310\python.exe
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-ad3bcefe-c273-3306-b92f-89b68886d6af
                host: abhi
                memory:
                    total: "33615630336"
                os: Windows-10-10.0.26200-SP0
                program: D:\IITM\da6401_a3\runs\q2_4_positional_encoding.py
                python: CPython 3.10.11
                root: D:\IITM\da6401_a3
                startedAt: "2026-05-10T11:54:09.344626Z"
                writerId: 86c178espjtm0w2qo7t5l9964kzlwbc3
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 33
            "2":
                - 1
                - 33
            "3":
                - 2
                - 13
            "4": 3.10.11
            "5": 0.25.1
            "8":
                - 3
            "10":
                - 20
            "12": 0.25.1
            "13": windows-amd64
